# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
  - r: devel
  - stage: full
    os: osx
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    #before_deploy:
    #- Rscript -e 'remotes::install_cran("pkgdown")'
    #deploy:
    #  provider: script
    #  script: Rscript -e 'pkgdown::deploy_site_github()'
    #  skip_cleanup: true
  - r: 3.4
  - r: release
    install:
      - Rscript -e 'install.packages("devtools")'
      - Rscript -e 'devtools::install_version("dplyr", version = "0.8.0",upgrade="never")'
      - Rscript -e 'devtools::install_version("readxl", version = "1.0.0",upgrade="never")'
      - Rscript -e 'devtools::install_version("rvest", version = "0.3.2",upgrade="never")'
      - Rscript -e 'devtools::install_version("lubridate", version = "1.7.0",upgrade="never")'
      - Rscript -e 'devtools::install_version("purrr", version = "0.2.5",upgrade="never")'
      - Rscript -e 'devtools::install_version("readr", version = "1.0.0",upgrade="never")'
      - Rscript -e 'devtools::install_version("rstudioapi", version = "0.2",upgrade="never")'
      - Rscript -e 'devtools::install_version("xml2", version = "1.2.0",upgrade="never")'

matrix:
  fast_finish: true
